# Use the official Node.js image
FROM node:22

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the local code to the container image
COPY . .

# Make the port available to the world outside this container
EXPOSE 5173

# Run the backend server
CMD ["npm", "run", "dev"]
